apiVersion: kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: add-certificates-volume
spec:
  rules:
    - name: add-ssl-certs-and-env
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.metadata.annotations.\"inject-certs\" || '' }}"
          operator: Equals
          value: enabled
      mutate:
        patchStrategicMerge:
          spec:
            volumes:
              - name: etc-ssl-certs
                configMap:
                  name: ca-pemstore
            containers:
              - (name): "*"
                volumeMounts:
                  - name: etc-ssl-certs
                    mountPath: /etc/ssl/certs
                env:
                  - name: SSL_CERT_FILE
                    value: /etc/ssl/certs/ca.crt

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-lab
configMapGenerator:
- name: ca-pemstore
  files:
  - ca.crt=root-ca.crt

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
configMapGenerator:
- name: ca-pemstore
  files:
  - ca.crt=root-ca.crt