apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: minio-nfs-pv