
#=================================================================================
#   Remeber to configure storage for this profile. (storage/s3-storage.yml)
#=================================================================================
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: llm-lab       # 1. Choose their namespace name
spec:
  owner:
    kind: User
    name: "ntiamoah376@yahoo.com" # 2. Enter their Keycloak email
---
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: gpu-tolerations
  namespace: llm-lab
spec:
  selector:
    matchLabels:
      gpu-tolerations: "true" # This is the label to match
      inject-shared-resource: "enabled"   # Kyverno injects CA and S3 credentials
  tolerations: # Your tolerations configuration
    - key: "dedicated"
      operator: "Equal"
      value: "gpu"
      effect: "NoExecute"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: llm-lab-compute-quota
  namespace: llm-lab # Target your user workspace namespace
spec:
  hard:
    # CPU and Memory ceilings across all pods in this namespace combined
    requests.cpu: "2"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 64Gi

    requests.nvidia.com/gpu: "10"
    
    # Restrict total object counts to prevent cluster clutter
    pods: "20"
    count/statefulsets: "2" # Limits the number of concurrent Notebook servers
    persistentvolumeclaims: "3" # Limits total volume claims
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-user-limits
spec:
  limits:
  - default: # Default limits if not specified
      cpu: "2"
      memory: 4Gi
    defaultRequest: # Default requests if not specified
      cpu: "1"
      memory: 2Gi
    type: Container
